// Factory Presets for Syna Synthesizer

import { SynthParams, defaultParams } from './engine';
import { EffectParams, defaultEffectParams } from './effects';

export interface Preset {
  name: string;
  category: string;
  synth: SynthParams;
  effects: EffectParams;
}

export const factoryPresets: Preset[] = [
  // === INIT / BASIC ===
  {
    name: 'Init',
    category: 'Basic',
    synth: { ...defaultParams },
    effects: { ...defaultEffectParams },
  },

  // === BASS ===
  {
    name: 'Fat Bass',
    category: 'Bass',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 1.0,
      osc2Waveform: 'saw',
      osc2Detune: 10,
      osc2Level: 0.8,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 400,
      filterResonance: 0.3,
      filterEnvAmount: 0.4,
      ampAttack: 0.005,
      ampDecay: 0.3,
      ampSustain: 0.6,
      ampRelease: 0.2,
      filterAttack: 0.01,
      filterDecay: 0.2,
      filterSustain: 0.2,
      filterRelease: 0.1,
      masterVolume: 0.8,
    },
    effects: {
      reverbMix: 0.1,
      reverbDecay: 1.0,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      
      delayTime: 0.0,
      delayFeedback: 0.0,
      delayMix: 0.0,
      chorusRate: 0.0,
      chorusDepth: 0.0,
      chorusMix: 0.0,
    },
  },
  {
    name: 'Sub Bass',
    category: 'Bass',
    synth: {
      osc1Waveform: 'sine',
      osc1Level: 1.0,
      osc2Waveform: 'sine',
      osc2Detune: 0,
      osc2Level: 0.0,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 200,
      filterResonance: 0.0,
      filterEnvAmount: 0.2,
      ampAttack: 0.01,
      ampDecay: 0.1,
      ampSustain: 0.9,
      ampRelease: 0.3,
      filterAttack: 0.01,
      filterDecay: 0.1,
      filterSustain: 0.8,
      filterRelease: 0.2,
      masterVolume: 0.9,
    },
    effects: {
      ...defaultEffectParams,
      reverbMix: 0.0,
    },
  },
  {
    name: 'Moog Bass',
    category: 'Bass',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 0.8,
      osc2Waveform: 'saw',
      osc2Detune: 5,
      osc2Level: 0.6,
      subLevel: 0.7,  // Sub osc for that Moog thickness
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 300,
      filterResonance: 0.5,  // Resonant filter
      filterEnvAmount: 0.6,
      ampAttack: 0.001,
      ampDecay: 0.2,
      ampSustain: 0.5,
      ampRelease: 0.15,
      filterAttack: 0.001,
      filterDecay: 0.15,
      filterSustain: 0.2,
      filterRelease: 0.1,
      masterVolume: 0.75,
    },
    effects: {
      reverbMix: 0.05,
      reverbDecay: 0.8,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      
      delayTime: 0.0,
      delayFeedback: 0.0,
      delayMix: 0.0,
      chorusRate: 0.0,
      chorusDepth: 0.0,
      chorusMix: 0.0,
    },
  },

  // === LEADS ===
  {
    name: 'Classic Lead',
    category: 'Lead',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 1.0,
      osc2Waveform: 'square',
      osc2Detune: 5,
      osc2Level: 0.5,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 2000,
      filterResonance: 0.4,
      filterEnvAmount: 0.5,
      ampAttack: 0.01,
      ampDecay: 0.2,
      ampSustain: 0.7,
      ampRelease: 0.3,
      filterAttack: 0.01,
      filterDecay: 0.3,
      filterSustain: 0.4,
      filterRelease: 0.2,
      masterVolume: 0.7,
    },
    effects: {
      reverbMix: 0.25,
      reverbDecay: 1.5,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      
      delayTime: 0.33,
      delayFeedback: 0.3,
      delayMix: 0.2,
      chorusRate: 0.0,
      chorusDepth: 0.0,
      chorusMix: 0.0,
    },
  },
  {
    name: 'Screamer',
    category: 'Lead',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 1.0,
      osc2Waveform: 'saw',
      osc2Detune: 7,
      osc2Level: 1.0,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 4000,
      filterResonance: 0.6,
      filterEnvAmount: 0.3,
      ampAttack: 0.005,
      ampDecay: 0.1,
      ampSustain: 0.8,
      ampRelease: 0.2,
      filterAttack: 0.01,
      filterDecay: 0.2,
      filterSustain: 0.6,
      filterRelease: 0.15,
      masterVolume: 0.6,
    },
    effects: {
      reverbMix: 0.3,
      reverbDecay: 2.0,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      
      delayTime: 0.25,
      delayFeedback: 0.4,
      delayMix: 0.25,
      chorusRate: 2.0,
      chorusDepth: 0.4,
      chorusMix: 0.3,
    },
  },
  {
    name: 'Moog Lead',
    category: 'Lead',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 1.0,
      osc2Waveform: 'square',
      osc2Detune: 3,
      osc2Level: 0.7,
      subLevel: 0.4,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 1800,
      filterResonance: 0.55,
      filterEnvAmount: 0.6,
      ampAttack: 0.005,
      ampDecay: 0.15,
      ampSustain: 0.75,
      ampRelease: 0.25,
      filterAttack: 0.005,
      filterDecay: 0.2,
      filterSustain: 0.4,
      filterRelease: 0.2,
      masterVolume: 0.65,
    },
    effects: {
      reverbMix: 0.2,
      reverbDecay: 1.5,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.25,
      delayFeedback: 0.3,
      delayMix: 0.15,
      chorusRate: 0.0,
      chorusDepth: 0.0,
      chorusMix: 0.0,
    },
  },

  // === PADS ===
  {
    name: 'Soft Pad',
    category: 'Pad',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 0.7,
      osc2Waveform: 'saw',
      osc2Detune: 12,
      osc2Level: 0.7,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 1500,
      filterResonance: 0.2,
      filterEnvAmount: 0.3,
      ampAttack: 0.5,
      ampDecay: 0.5,
      ampSustain: 0.8,
      ampRelease: 1.0,
      filterAttack: 0.3,
      filterDecay: 0.5,
      filterSustain: 0.6,
      filterRelease: 0.8,
      masterVolume: 0.6,
    },
    effects: {
      reverbMix: 0.5,
      reverbDecay: 3.0,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.4,
      delayFeedback: 0.3,
      delayMix: 0.15,
      chorusRate: 0.8,
      chorusDepth: 0.5,
      chorusMix: 0.4,
    },
  },
  {
    name: 'Warm Strings',
    category: 'Pad',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 0.6,
      osc2Waveform: 'saw',
      osc2Detune: 8,
      osc2Level: 0.6,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 2500,
      filterResonance: 0.1,
      filterEnvAmount: 0.2,
      ampAttack: 0.8,
      ampDecay: 0.3,
      ampSustain: 0.9,
      ampRelease: 1.2,
      filterAttack: 0.5,
      filterDecay: 0.3,
      filterSustain: 0.7,
      filterRelease: 0.8,
      masterVolume: 0.6,
    },
    effects: {
      reverbMix: 0.45,
      reverbDecay: 2.5,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.0,
      delayFeedback: 0.0,
      delayMix: 0.0,
      chorusRate: 1.2,
      chorusDepth: 0.6,
      chorusMix: 0.5,
    },
  },
  {
    name: 'Dark Atmosphere',
    category: 'Pad',
    synth: {
      osc1Waveform: 'square',
      osc1Level: 0.5,
      osc2Waveform: 'triangle',
      osc2Detune: 3,
      osc2Level: 0.8,
      subLevel: 0.0,
      noiseLevel: 0.15,  // Subtle noise for atmosphere
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 800,
      filterResonance: 0.3,
      filterEnvAmount: 0.4,
      ampAttack: 1.0,
      ampDecay: 0.5,
      ampSustain: 0.7,
      ampRelease: 2.0,
      filterAttack: 0.8,
      filterDecay: 1.0,
      filterSustain: 0.3,
      filterRelease: 1.5,
      masterVolume: 0.5,
    },
    effects: {
      reverbMix: 0.6,
      reverbDecay: 4.0,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.5,
      delayFeedback: 0.5,
      delayMix: 0.3,
      chorusRate: 0.3,
      chorusDepth: 0.7,
      chorusMix: 0.4,
    },
  },

  // === PLUCKS ===
  {
    name: 'Pluck',
    category: 'Pluck',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 1.0,
      osc2Waveform: 'triangle',
      osc2Detune: 0,
      osc2Level: 0.3,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 3000,
      filterResonance: 0.2,
      filterEnvAmount: 0.7,
      ampAttack: 0.001,
      ampDecay: 0.3,
      ampSustain: 0.0,
      ampRelease: 0.2,
      filterAttack: 0.001,
      filterDecay: 0.2,
      filterSustain: 0.1,
      filterRelease: 0.15,
      masterVolume: 0.7,
    },
    effects: {
      reverbMix: 0.35,
      reverbDecay: 1.8,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.25,
      delayFeedback: 0.25,
      delayMix: 0.2,
      chorusRate: 0.0,
      chorusDepth: 0.0,
      chorusMix: 0.0,
    },
  },
  {
    name: 'Electric Piano',
    category: 'Pluck',
    synth: {
      osc1Waveform: 'sine',
      osc1Level: 1.0,
      osc2Waveform: 'triangle',
      osc2Detune: 0,
      osc2Level: 0.4,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 4000,
      filterResonance: 0.1,
      filterEnvAmount: 0.5,
      ampAttack: 0.001,
      ampDecay: 0.8,
      ampSustain: 0.3,
      ampRelease: 0.5,
      filterAttack: 0.001,
      filterDecay: 0.5,
      filterSustain: 0.3,
      filterRelease: 0.3,
      masterVolume: 0.7,
    },
    effects: {
      reverbMix: 0.3,
      reverbDecay: 2.0,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.0,
      delayFeedback: 0.0,
      delayMix: 0.0,
      chorusRate: 2.5,
      chorusDepth: 0.3,
      chorusMix: 0.25,
    },
  },

  // === KEYS ===
  {
    name: 'Organ',
    category: 'Keys',
    synth: {
      osc1Waveform: 'sine',
      osc1Level: 1.0,
      osc2Waveform: 'sine',
      osc2Detune: 0,
      osc2Level: 0.0,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 8000,
      filterResonance: 0.0,
      filterEnvAmount: 0.0,
      ampAttack: 0.01,
      ampDecay: 0.05,
      ampSustain: 1.0,
      ampRelease: 0.1,
      filterAttack: 0.01,
      filterDecay: 0.1,
      filterSustain: 1.0,
      filterRelease: 0.1,
      masterVolume: 0.6,
    },
    effects: {
      reverbMix: 0.25,
      reverbDecay: 1.5,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.0,
      delayFeedback: 0.0,
      delayMix: 0.0,
      chorusRate: 6.0,
      chorusDepth: 0.2,
      chorusMix: 0.3,
    },
  },

  // === FX / SPECIAL ===
  {
    name: 'Shimmer',
    category: 'FX',
    synth: {
      osc1Waveform: 'triangle',
      osc1Level: 0.8,
      osc2Waveform: 'sine',
      osc2Detune: 24, // Octave up feel
      osc2Level: 0.4,
      subLevel: 0.0,
      noiseLevel: 0.0,
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 6000,
      filterResonance: 0.3,
      filterEnvAmount: 0.4,
      ampAttack: 0.3,
      ampDecay: 0.4,
      ampSustain: 0.6,
      ampRelease: 1.5,
      filterAttack: 0.2,
      filterDecay: 0.3,
      filterSustain: 0.5,
      filterRelease: 1.0,
      masterVolume: 0.5,
    },
    effects: {
      reverbMix: 0.7,
      reverbDecay: 4.5,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.33,
      delayFeedback: 0.5,
      delayMix: 0.4,
      chorusRate: 1.0,
      chorusDepth: 0.5,
      chorusMix: 0.4,
    },
  },
  {
    name: 'Ambient Drone',
    category: 'FX',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 0.4,
      osc2Waveform: 'square',
      osc2Detune: 5,
      osc2Level: 0.4,
      subLevel: 0.3,  // Deep sub for drone
      noiseLevel: 0.1,  // Subtle noise texture
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 600,
      filterResonance: 0.5,
      filterEnvAmount: 0.2,
      ampAttack: 2.0,
      ampDecay: 1.0,
      ampSustain: 0.8,
      ampRelease: 3.0,
      filterAttack: 1.5,
      filterDecay: 2.0,
      filterSustain: 0.3,
      filterRelease: 2.0,
      masterVolume: 0.4,
    },
    effects: {
      reverbMix: 0.8,
      reverbDecay: 6.0,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.66,
      delayFeedback: 0.6,
      delayMix: 0.5,
      chorusRate: 0.2,
      chorusDepth: 0.8,
      chorusMix: 0.5,
    },
  },
  {
    name: 'Noise Sweep',
    category: 'FX',
    synth: {
      osc1Waveform: 'saw',
      osc1Level: 0.3,
      osc2Waveform: 'square',
      osc2Detune: 0,
      osc2Level: 0.0,
      subLevel: 0.0,
      noiseLevel: 0.8,  // Heavy noise
      fmAmount: 0.0,
      fmRatio: 2.0,
      filterCutoff: 400,
      filterResonance: 0.7,  // Resonant sweep
      filterEnvAmount: 0.9,
      ampAttack: 0.5,
      ampDecay: 1.5,
      ampSustain: 0.4,
      ampRelease: 2.0,
      filterAttack: 0.3,
      filterDecay: 2.0,
      filterSustain: 0.1,
      filterRelease: 1.5,
      masterVolume: 0.5,
    },
    effects: {
      reverbMix: 0.6,
      reverbDecay: 4.0,
      reverbPreDelay: 0.02,
      reverbDamping: 0.5,
      delayTime: 0.33,
      delayFeedback: 0.4,
      delayMix: 0.3,
      chorusRate: 0.5,
      chorusDepth: 0.4,
      chorusMix: 0.3,
    },
  },

];

// Get presets grouped by category
export function getPresetsByCategory(): Map<string, Preset[]> {
  const categories = new Map<string, Preset[]>();

  for (const preset of factoryPresets) {
    if (!categories.has(preset.category)) {
      categories.set(preset.category, []);
    }
    categories.get(preset.category)!.push(preset);
  }

  return categories;
}

// Get preset by name
export function getPresetByName(name: string): Preset | undefined {
  return factoryPresets.find((p) => p.name === name);
}
